import time
from skills.task_processor import TaskProcessor

# Create a test task file in needs_action
test_task_content = "Task: Research top 3 MCP servers for Gmail integration and list their features."
needs_action_path = "obsidian_vault/needs_action"
plans_path = "obsidian_vault/Plans"

# Write the test file
with open(f"{needs_action_path}/test_task_metadata.md", 'w') as f:
    f.write("# Task Metadata\n\n**Original File:** test_task.md\n**Detected At:** 2026-02-11 19:59:12\n**Status:** Pending\n**Action Required:** Review and process this task\n\n---\n*This file was automatically generated by the AI Employee.*\n\nTask: Research top 3 MCP servers for Gmail integration and list their features.")

# Create and run the task processor
processor = TaskProcessor(needs_action_path, plans_path)
processor.process_task_file(f"{needs_action_path}/test_task_metadata.md")

print("Task processed. Check the Plans folder for the generated plan.")