import os
from datetime import datetime
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
from skills.base_watcher import BaseWatcher


class FilesystemWatcher(BaseWatcher):
    """
    Concrete implementation of BaseWatcher that monitors filesystem changes.
    Specifically designed to watch for new .md files in a specified directory.
    """
    
    def __init__(self, monitored_path: str, output_path: str):
        super().__init__(monitored_path)
        self.output_path = output_path
        self.observer = Observer()
        self.event_handler = FileCreatedHandler(self)
        
    def start_monitoring(self):
        """Start the filesystem monitoring process"""
        self.ensure_directory_exists(self.output_path)
        self.observer.schedule(self.event_handler, self.monitored_path, recursive=False)
        self.observer.start()
        self.is_running = True
        print(f"Started monitoring {self.monitored_path}")
        
    def stop_monitoring(self):
        """Stop the filesystem monitoring process"""
        self.observer.stop()
        self.observer.join()
        self.is_running = False
        print("Stopped monitoring")
        
    def handle_new_file(self, file_path: str):
        """Handle a newly detected file by creating a metadata file"""
        self.create_metadata_file(file_path)
    
    def create_metadata_file(self, original_file_path: str):
        """Create a metadata .md file in the output directory"""
        filename = os.path.basename(original_file_path)
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        # Create metadata content
        metadata_content = f"""# Task Metadata
        
**Original File:** {filename}
**Detected At:** {timestamp}
**Status:** Pending
**Action Required:** Review and process this task

---
*This file was automatically generated by the AI Employee.*
"""
        
        # Generate metadata filename
        name_without_ext = os.path.splitext(filename)[0]
        metadata_filename = f"{name_without_ext}_metadata.md"
        metadata_path = os.path.join(self.output_path, metadata_filename)
        
        # Write metadata file
        with open(metadata_path, 'w', encoding='utf-8') as f:
            f.write(metadata_content)
        
        print(f"Created metadata file: {metadata_filename}")


class FileCreatedHandler(FileSystemEventHandler):
    """
    Event handler for filesystem events.
    """
    
    def __init__(self, watcher_instance):
        self.watcher = watcher_instance
    
    def on_created(self, event):
        if not event.is_directory:
            print(f"New file detected: {os.path.basename(event.src_path)}")
            self.watcher.handle_new_file(event.src_path)